repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: unresolved-import
        additional_dependencies:
          - 'optional-module-name'
          - 'another-optional-module-name'