name: Bug Report
description: Submit a bug report
title: "[Bug Report] Bug title"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: |
        Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: system-info
    attributes:
      label: System info
      description: |
        Describe the characteristic of your environment:
        * Describe how Gymnasium was installed (pip, docker, source, ...)
        * Version of `gymnasium` (by `gymnasium.__version__`)
        * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.
        * Python version

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: >
            I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in
            the repo
          required: true
