name: Proposal
description: Propose changes that are not fixing bugs
title: "[Proposal] Proposal title"
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: A clear and concise description of the proposal.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Please outline the motivation for the proposal.
        Is your feature request related to a problem? e.g.,"I'm always frustrated when [...]".
        If this is related to another GitHub issue, please link here too.

  - type: textarea
    id: pitch
    attributes:
      label: Pitch
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered, if any.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: >
            I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in
            the repo
          required: true
