name: Question
description: Ask a question
title: "[Question] Question title"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: >
        If you're a beginner and have basic questions, please ask on
        [r/reinforcementlearning](https://www.reddit.com/r/reinforcementlearning/) or in the
        [RL Discord](https://discord.com/invite/xhfNqQv) (if you're new please use the beginners channel).
        Basic questions that are not bugs or feature requests will be closed without reply, because GitHub
        issues are not an appropriate venue for these. Advanced/nontrivial questions, especially in areas where
        documentation is lacking, are very much welcome.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Your question
    validations:
      required: true
